### ISSUE TITLE
Serve Sphinx Documentation

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#194]
- [x] Work out a way to serve documentation. Possibly with github pages, as in [these instructions](https://python.plainenglish.io/how-to-host-your-sphinx-documentation-on-github-550254f325ae)
- [x] If there are other options, briefly present the pros and cons (the solution must be free)
- [x] Serve documentation on chosen platform

**Comment by jwestw** [comment]
@nkshaw23 will be working with @paigeh1 to get this over the line.

**Comment by nkshaw23** [comment]
@jwestw can you confirm what [publishing source](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) we have setup on the repo?

**Comment by james-westwood** [comment]
Hi Nathan. I'm not sure what you mean by this. What's the publishing
source? I have very limited network here but will try to help if I can.

**Comment by nkshaw23** [comment]
No problem if you cant look James - we can just pick up next week!

For publishing source got to settings -> Code and automation -> GitHub Pages. What folder is selected for the publishing source?

![image](https://user-images.githubusercontent.com/20166290/170951727-13e18b02-0e8a-41e1-b844-4e37f1be57c3.png)

**Comment by nkshaw23** [comment]
Docs now serving with CSS. I set up a folder named `html` to build everything into (rather than `build`) and then had to add two files in `docs`:

1) `index.html` which redirects to the index file within `html`.
2) empty `.nojekyll` (which Paige had already created)

Then run `sphinx-build -b html docs/source docs/html` to build the docs and add/commit. Im sure there is a cleaner way to do this, but thought worth documenting so we have a working copy.

A few things to note:

1) I'm sure more folders could be ignored (`docs/doctrees` and `docs/html`) but had trouble with `.gitignore` trying this.
2) I think `build` can now be deleted (which is currently being ignored)
3) The two FTP module dont have docs because the script is failing when trying to access FTP.

**Comment by nkshaw23** [comment]
Check docstring in final function in geospatial mods - mentions it might be removed.

**Comment by nkshaw23** [comment]
@james-westwood to close issue once #118 has been merged (now ready).

**Comment by jwestw** [comment]
Closing issue as Paige merged https://github.com/ONSdigital/SDG_11.2.1/commit/d8cab5de9d698002fe6567d8ba074bdbc20aac56
