### ISSUE TITLE
Get developer environment set up

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#222]
@nkshaw23 I can't assign this to you until you are added to the repo

- Follow instructions in the readme to get your environment set up. (we suggest using VS Code)
- Make suggestions to update the README if applicable (maybe make a branch/pull request) 

Note: there is a "For developers" section in the [README of my other project](https://github.com/jwestw/Public_Transport_Efficiency/blob/develop/README.md), which might be good to look at.

**Comment by nkshaw23** [comment]
I seem to be setup on personal machine. Running into trouble when trying to access the FTP but assume this is a permissions thing. A couple of points to note on getting setup (not sure if worth adding to the readme).

1) I cant use powershell as a terminal in vs code. I am using cmd.
2) In order to create the conda virtual environment I had to do the [following steps](https://stackoverflow.com/questions/50125472/issues-with-installing-python-libraries-on-windows-condahttperror-http-000-co/62483686#62483686) - the original error I received was that the HTTP connection failed when trying to collect the package metadata.
3) #225  is looking at this, but had to remove gptables from requirements to run.

**Comment by nkshaw23** [comment]
Setup complete - adding thoughts for future users through this ticket #230
