### ISSUE TITLE
Explore bus time table API

### ISSUE THREAD

**Issue by nkshaw23** [ONSdigital/SDG_11.2.1#257]
The [Bus open data service](https://data.bus-data.dft.gov.uk/api/) managed by DFT provides API access to timetable data for bus journeys. Explore the data, make notes on its suitability and parse it.

Overall data catlouge can be accessed here [https://data.bus-data.dft.gov.uk/guidance/requirements/?section=datacatalogue](https://data.bus-data.dft.gov.uk/guidance/requirements/?section=datacatalogue).

Free acocunt needs to be created to access data.

For reference - links to other countries methodologies that integrate highly serviced stops

Estonia: https://www.efgs.info/11-2-1-estonia/
Norway: https://www.efgs.info/11-2-1-norway-test-page/
Sweden: https://www.efgs.info/11-2-1-sweden/

**Comment by nkshaw23** [comment]
All data can be accessed either in TransXChange format (XML) or GTFS (CSV) and is updated twice daily. We are interested in the timetables data.

XML data can be accessed via the API whereas the GTFS data is available as a [zipped download](https://data.bus-data.dft.gov.uk/timetable/download/) from the site. Although they are the same dataset, they have very different structures.

Due to the complexity of parser through various branches of the XML file (and working out the connecting IDs between these branches) we looked at the GTFS data.

The download contains several files with the most relevant for us in terms of calculating frequency being:

- `calender` which provides what day each service run 
- `stop_times` which provides the departure time for each stop
- `trips which details all trips (from start to finish destination)

This files can be linked between themselves, and then onto the naptan data to provide a geolocation (coordinates are provided in the CSV but not sure how these are calculated).

`calender` contains `service_id` which is contained in `trips.`
`trips` contains `trip_id` which is contained in `stop_times`
`stop_times` contains `stop_id` which, after testing a few records, looks to be the same as `ACTOCode` in the naptan dataset.

**Next steps:**

- Explore whether there is a way to filter only updated records when downloading each day.
- Create process for calculating highly serviced stops.
- Build a small working example (imagine some functions that already exist can be re-used).

**Comment by nkshaw23** [comment]
Attached diagram showing how downloaded GTFS data is linked and a rough process diagram for calculating highly serviced stops from this data.

![GTFS_bus_data_structure (1)](https://user-images.githubusercontent.com/20166290/183899593-8054f82c-0c4f-48cc-b2c3-34333c55e993.png)
![calculating_highly_serviced_bus_stops](https://user-images.githubusercontent.com/20166290/183899606-a7483aba-7e38-41be-ac1a-db12e147bdb5.png)

**Comment by nkshaw23** [comment]
Existing functions `_import_extract_delete_zip` and `_csv_to_df` can be used for downloading, extracting and loading data in pandas dataframe.

**Comment by jwestw** [comment]
> Existing functions _import_extract_delete_zip and _csv_to_df can be used for downloading, extracting and loading data in pandas dataframe.

Great. I really appreciate you looking into how we can use and adapt existing functions!

**Comment by jwestw** [comment]
Feedback and questions about the first diagram:
- Are there any routes that we would want to filter out? This is a completely open question as I have no preconceptions about what might skew results, but maybe there are some kind of special services or school services that on;y occur on certain days and therefore don't really represent an average work-day commute time. If this is the case maybe we could use calendar.txt to identify routes which are temporary. 
- It looks like the main file we need here is the stop times if we decide not to action anything on the first point I made. 
- I wonder if there's any difference between a set of the stop codes in stops.txt and stop_times.txt

Notes on diagram 2. 
- I think updating the stats yearly will be adequate. In a year's time we will not be re-running the pipeline ourselves which is why we need to make it robust, make the data inputs as automatic as possible and have good documentation. 
- Which three files do you think we need for analysis. I would say we just need the stops.txt and the stop_times.txt. Any reason to import the rest of them? I would suggest keeping things as streamlines as possible by importing just what we need. 
- Rather than extracting the hour, I would suggest filtering function which takes the day of the week and the hour-range as parameters and filters out the data outside of those days and times. 
- I like the idea of the frequency dataframe! Although at the moment this could be just a simple True/False for a service in that hour time frame, a count of services would be essential if we wanted to enhance the analysis by differentiating to what degree each stop is serviced. Stops that have a service every five minutes are more useful than those which have just one service an hour and therefore increase accessibility to the transport service. 
- At the stage of extracting highly serviced stops, the default could be 1, but it would be really interesting to see how many people have access to 2, 3 and more services per hour and plot those.  
- 

-

**Comment by nkshaw23** [comment]
Based on discussions with @jwestw and the process diagram above, the following tasks have been created:

- [ #277 ]

**Comment by nkshaw23** [comment]
Closed by #327
