### ISSUE TITLE
Produce Aggregate Estimate NI

### ISSUE THREAD

**Issue by Antonio-John** [ONSdigital/SDG_11.2.1#304]
-Once #270, #288 & #306 are complete we will be able to produce an estimate for NI per local authority.

**Comment by paigeh1** [comment]
It also might be worth changing the read_ni_stops function to just outputting a pandas dataframe as another function we need to use converts it into a geopandas dataframe.

**Comment by paigeh1** [comment]
There is a current issue with the code - when I run it, it's not finding the stops inside the polygon for the local authority and it can't find the population total.

**Comment by paigeh1** [comment]
Summary of discussion with @nkshaw23 : 

- The coordinates system for Easting and Northing (that was currently being used for NI) is incorrect for both trains and buses NI data.
- Latitude and Longitude will be used instead as the projections for this are correct. This will then be converted into the correct coordinates system. However, this is not present in the NI trains csv file, and only extracted from the geojson file. We have decided to produce a hard CSV copy and upload it onto sync.
- Commas present in `pop_count` or other columns will need to be removed from all cells so we can change the dtype to int.
- We are going to correctly populate easting and northing coordinates for both bus and train stops so we have 2 coordinate systems to use.
- Going to tidy the `stops_geo_df` so it is a clean copy for potential future use.
- Have decided not to read in NI bus stops data via a URL link because the URLs tend to update frequently (this has happened before), so it cannot read in the data correctly and will create a bug in our code. Instead, the bus stops will be stored on sync.

**Comment by paigeh1** [comment]
Note to self: I didn't pull the commits from master so I need to pull all commits from master then rebase the branch.
