### ISSUE TITLE
Read in Centroid Data NI

### ISSUE THREAD

**Issue by Antonio-John** [ONSdigital/SDG_11.2.1#306]
# Steps for Developer:

-Read in centroid data. Do we have this data already contained in our current centroid file? Or will we have to source this separately?
- Once sourced, read in & merge onto the Small Areas population estimate dataset.

**Comment by paigeh1** [comment]
The population weighted centroids data is here: https://www.nisra.gov.uk/support/geography/northern-ireland-small-areas

I have downloaded this and will put on Sync

**Comment by paigeh1** [comment]
We need to re-open this because we are currently using geographically weighted centroids. We need to change this to population weighted centroids

**Comment by paigeh1** [comment]
We can't map the new small areas introduced in 2011 to the output areas that came in Census 2001. Because of this, we either use population weighted centroids and the statistics we use for small areas will now need to be for output areas (so 2001 data) or we use geographically weighted centroids still. Happy to have a chat about this @Antonio-John

**Comment by paigeh1** [comment]
There are duplicates for small areas in the output areas as more than one output area maps to a small area. We might need to make a union for the centroid so that all areas are covered. Will look into this.

**Comment by paigeh1** [comment]
Had discussion with @Antonio-John @nkshaw23 . Going to use the one-to-one mapping from SA to OA for population centroids rather than the average.

**Comment by jwestw** [comment]
Please make sure you add this to the working doc, so we can include it in our method write up later on.
